### ISSUE TITLE
Hardware Acceleration

### ISSUE THREAD

**Issue by gotnull** [innightwolfsleep/llm_telegram_bot#103]
Is there CUDA hardware acceleration support?

**Comment by innightwolfsleep** [comment]
As transformers and llama_cpp support CUDA, telegram_bot support too (you can choose betwen them in settings, "generator_script"). There is no recipie in readme how to use CUDA, reffer to original library (https://github.com/TimDettmers/bitsandbytes#requirements--installation https://github.com/huggingface/transformers#installation)

**Comment by innightwolfsleep** [comment]
+ added exllama
